<?php
/**
 * Created by PhpStorm.
 * User: 22258
 * Date: 2020/5/19
 * Time: 22:33
 */

namespace app\admin\controller;


class Admin extends Init{

    //继承父类
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    function edit(){
        if (request()->isPost()){
            $params = input('post.');
            if ($params['password'] && !empty($params['password'])){
                //将md5的字符串编码全部转换为小写
                $params['password'] = strtolower(md5($params['password']));
            }else{
                //销毁密码
                unserialize($params['password']);
            }
            $result = $this->model->edit($params);
            if ($result){
                session(null);
                return json(array('code'=>200,'msg'=>'修改成功'));
            }else{
                return json(array('code'=>0,'msg'=>'修改失败'));
            }
        }
        return view ('edit');
    }
}